## Numpy code

In [1]:
# !pip install numpy

In [2]:
import numpy as np

### np.array

In [3]:
l = [1, 2, 3, 4, 5]

In [4]:
npa = np.array(l)

In [5]:
type(l), type(npa)

(list, numpy.ndarray)

In [6]:
npa.shape

(5,)

In [7]:
l.append(6)
npa = np.array(l)
npa

array([1, 2, 3, 4, 5, 6])

In [8]:
l.append('string')
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [9]:
l1 = [2, 5, 7, 24]

In [10]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [11]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 2, 5, 7, 24]

In [12]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', '6', 'string', '2', '5', '7', '24'],
      dtype='<U11')

In [13]:
l + [10]

[1, 2, 3, 4, 5, 6, 'string', 10]

In [14]:
l = [[1, 2], [3, 4], [5, 6]]

In [15]:
# 2 dim
npa2d = np.array(l)

In [16]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
npa2d.shape

(3, 2)

In [18]:
# flot
npa2d = np.array(l, dtype='float')

In [19]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
npa2d = npa2d.astype('str')

In [22]:
npa2d[0][0]

'1.0'

In [23]:
npa2d[0][0] + str(1)

'1.01'

### `na.nan` and `np.inf`

In [24]:
np.nan 

nan

In [25]:
np.nan == np.nan

False

In [26]:
None == None

True

In [27]:
np.inf == np.inf

True

In [28]:
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], dtype='<U32')

In [29]:
npa2d = npa2d.astype('float')

In [30]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [31]:
npa2d = npa2d.astype('int')

In [32]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
npa2d = npa2d.astype('float')

In [34]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf 

In [35]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 5.,  6.]])

In [36]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [37]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [38]:
# flag 
flag = np.isnan(npa2d) | np.isinf(npa2d)

In [39]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [40]:
# positions flag
npa2d[flag]

array([nan, inf])

In [41]:
npa2d[flag] = 0

In [42]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

### Statistical Operations

In [43]:
# mean, var, std, med

In [44]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [45]:
npa2d.mean()

2.6666666666666665

In [46]:
npa2d.min()

0.0

In [47]:
npa2d.max()

6.0

In [48]:
npa2d.var()

5.222222222222222

In [49]:
npa2d.std()

2.2852182001336816

In [50]:
np.median(npa2d)

2.5

### `shape()`, `reschape`, `ravel()` 

In [51]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [52]:
npa2d.shape

(3, 2)

In [53]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 5., 6.]])

In [54]:
npa2d.reshape(1, 3)

ValueError: cannot reshape array of size 6 into shape (1,3)

In [55]:
npa2d.reshape(1, 6)

array([[0., 2., 3., 0., 5., 6.]])

In [56]:
npa2d.reshape(1, 6).ravel()

array([0., 2., 3., 0., 5., 6.])

In [57]:
npa2d.flatten()

array([0., 2., 3., 0., 5., 6.])