## Numpy code

In [2]:
# !pip install numpy

In [3]:
import numpy as np

### np.array

In [4]:
l = [1, 2, 3, 4, 5]

In [5]:
npa = np.array(l)

In [6]:
type(l), type(npa)

(list, numpy.ndarray)

In [7]:
npa.shape

(5,)

In [8]:
l.append(6)
npa = np.array(l)
npa

array([1, 2, 3, 4, 5, 6])

In [9]:
l.append('string')
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [10]:
l1 = [2, 5, 7, 24]

In [11]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [12]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 2, 5, 7, 24]

In [13]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', '6', 'string', '2', '5', '7', '24'],
      dtype='<U11')

In [15]:
l + [10]

[1, 2, 3, 4, 5, 6, 'string', 10]

In [16]:
l = [[1, 2], [3, 4], [5, 6]]

In [17]:
# 2 dim
npa2d = np.array(l)

In [18]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
npa2d.shape

(3, 2)

In [20]:
# flot
npa2d = np.array(l, dtype='float')

In [21]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
npa2d = npa2d.astype('str')

In [25]:
npa2d[0][0]

'1.0'

In [26]:
npa2d[0][0] + str(1)

'1.01'

### `na.nan` and `np.inf`

In [27]:
np.nan 

nan

In [28]:
np.nan == np.nan

False

In [29]:
None == None

True

In [30]:
np.inf == np.inf

True

In [32]:
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], dtype='<U32')

In [34]:
npa2d = npa2d.astype('float')

In [35]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [36]:
npa2d = npa2d.astype('int')

In [37]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
npa2d = npa2d.astype('float')

In [39]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf 

In [40]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 5.,  6.]])

In [41]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [42]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [43]:
# flag 
flag = np.isnan(npa2d) | np.isinf(npa2d)

In [44]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [45]:
# positions flag
npa2d[flag]

array([nan, inf])

In [46]:
npa2d[flag] = 0

In [47]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])