## Numpy code

In [2]:
# !pip install numpy

In [3]:
import numpy as np

### np.array

In [4]:
l = [1, 2, 3, 4, 5]

In [5]:
npa = np.array(l)

In [6]:
type(l), type(npa)

(list, numpy.ndarray)

In [7]:
npa.shape

(5,)

In [8]:
l.append(6)
npa = np.array(l)
npa

array([1, 2, 3, 4, 5, 6])

In [9]:
l.append('string')
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [10]:
l1 = [2, 5, 7, 24]

In [11]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [12]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 2, 5, 7, 24]

In [13]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', '6', 'string', '2', '5', '7', '24'],
      dtype='<U11')

In [15]:
l + [10]

[1, 2, 3, 4, 5, 6, 'string', 10]

In [16]:
l = [[1, 2], [3, 4], [5, 6]]

In [17]:
# 2 dim
npa2d = np.array(l)

In [18]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
npa2d.shape

(3, 2)

In [20]:
# flot
npa2d = np.array(l, dtype='float')

In [21]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
npa2d = npa2d.astype('str')

In [25]:
npa2d[0][0]

'1.0'

In [26]:
npa2d[0][0] + str(1)

'1.01'