## Numpy

In [1]:
# Versão da Linguagem Python

from platform import python_version
print('Versão de Python Neste Jupyter Notebook:', python_version())

Versão de Python Neste Jupyter Notebook: 3.10.5


In [2]:
#imports necessários

import numpy as np                    # manipulação numerica
import warnings                       # silecio de alertas

warnings.filterwarnings('ignore')

In [3]:
# o pacote watermark adiciona um logotipo ao nosso notebook com as versões dos pacotes utilizados

%reload_ext watermark
%watermark -a "Caique Miranda" -gu caiquemiranda

print(f'Versão do Numpy {np.__version__}')

Author: Caique Miranda

Github username: caiquemiranda

Versão do Numpy 1.23.0


In [4]:
# !pip install numpy

### np.array

In [5]:
l = [1, 2, 3, 4, 5]

In [6]:
npa = np.array(l)

In [7]:
type(l), type(npa)

(list, numpy.ndarray)

In [8]:
npa.shape

(5,)

In [9]:
l.append(6)
npa = np.array(l)
npa

array([1, 2, 3, 4, 5, 6])

In [10]:
l.append('string')
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [11]:
l1 = [2, 5, 7, 24]

In [12]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [13]:
l + l1

[1, 2, 3, 4, 5, 6, 'string', 2, 5, 7, 24]

In [14]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', '6', 'string', '2', '5', '7', '24'],
      dtype='<U11')

In [15]:
l + [10]

[1, 2, 3, 4, 5, 6, 'string', 10]

In [16]:
l = [[1, 2], [3, 4], [5, 6]]

In [17]:
# 2 dim
npa2d = np.array(l)

In [18]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
npa2d.shape

(3, 2)

In [20]:
# flot
npa2d = np.array(l, dtype='float')

In [21]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
npa2d = npa2d.astype('str')

In [24]:
npa2d[0][0]

'1.0'

In [25]:
npa2d[0][0] + str(1)

'1.01'

### `na.nan` and `np.inf`

In [26]:
np.nan 

nan

In [27]:
np.nan == np.nan

False

In [28]:
None == None

True

In [29]:
np.inf == np.inf

True

In [30]:
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], dtype='<U32')

In [31]:
npa2d = npa2d.astype('float')

In [32]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [33]:
npa2d = npa2d.astype('int')

In [34]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
npa2d = npa2d.astype('float')

In [36]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf 

In [37]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 5.,  6.]])

In [38]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [39]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [40]:
# flag 
flag = np.isnan(npa2d) | np.isinf(npa2d)

In [41]:
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [42]:
# positions flag
npa2d[flag]

array([nan, inf])

In [43]:
npa2d[flag] = 0

In [44]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

### Statistical Operations

In [45]:
# mean, var, std, med

In [46]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [47]:
npa2d.mean()

2.6666666666666665

In [48]:
npa2d.min()

0.0

In [49]:
npa2d.max()

6.0

In [50]:
npa2d.var()

5.222222222222222

In [51]:
npa2d.std()

2.2852182001336816

In [52]:
np.median(npa2d)

2.5

### `shape()`, `reschape`, `ravel()` 

In [53]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [54]:
npa2d.shape

(3, 2)

In [55]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 5., 6.]])

In [56]:
npa2d.reshape(1, 3)

ValueError: cannot reshape array of size 6 into shape (1,3)

In [57]:
npa2d.reshape(1, 6)

array([[0., 2., 3., 0., 5., 6.]])

In [58]:
npa2d.reshape(1, 6).ravel()

array([0., 2., 3., 0., 5., 6.])

In [59]:
npa2d.flatten()

array([0., 2., 3., 0., 5., 6.])

### Sequence, repetions and random numbers
`arange()`, `linspace`, `random()`, `zeros()` and `ones`  

In [60]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [61]:
np.arange(1, 5, dtype='float')

array([1., 2., 3., 4.])

In [62]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [63]:
np.linspace(1, 20, 3)

array([ 1. , 10.5, 20. ])

In [64]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [65]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [66]:
np.zeros([1, 5])

array([[0., 0., 0., 0., 0.]])

In [67]:
np.zeros([1, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
np.ones([1, 2])

array([[1., 1.]])

In [69]:
np.ones([10, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
# sequences
np.tile([1, 2], 3)

array([1, 2, 1, 2, 1, 2])

In [71]:
np.repeat([1, 2], 3)

array([1, 1, 1, 2, 2, 2])

In [72]:
np.random.rand(3, 3)

array([[0.35279371, 0.4153681 , 0.78251742],
       [0.84931914, 0.20275764, 0.38894646],
       [0.19154633, 0.80999427, 0.72954296]])

In [73]:
np.random.randint(0, 100, [3, 3])

array([[53,  1, 25],
       [69, 42, 60],
       [83, 11, 19]])

In [74]:
np.random.seed(1)
np.random.randint(0, 100, [3, 3])

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

In [75]:
np.unique(npa2d)

array([0., 2., 3., 5., 6.])

In [76]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [77]:
np.unique(npa2d, return_counts=True)

(array([0., 2., 3., 5., 6.]), array([2, 1, 1, 1, 1], dtype=int64))

### `where()`

In [78]:
arr = np.array([8, 94, 8, 56, 1, 3, 4, 5, 7])

In [79]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [80]:
np.where( arr > 10 )

(array([1, 3], dtype=int64),)

In [81]:
index = np.where( arr > 10 )
arr[index]

array([94, 56])

In [82]:
index = np.where( arr < 10 )
arr[index]

array([8, 8, 1, 3, 4, 5, 7])

In [83]:
index = np.where( arr == 10 )
arr[index]

array([], dtype=int32)

In [84]:
arr > 10

array([False,  True, False,  True, False, False, False, False, False])

In [85]:
arr[arr > 10]

array([94, 56])

In [86]:
arr.max()

94

In [87]:
arr.argmax()

1

In [88]:
arr.argmin()

4

In [89]:
arr[arr.argmin()]

1

### File read and write

In [90]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [91]:
np.savetxt('data/npa2d.csv', npa2d, delimiter=',')

In [92]:
np.loadtxt('data/npa2d.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [93]:
np.save('data/data.npy', npa2d)

In [94]:
np.load('data/data.npy')

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [95]:
np.savez('data/both.npz', arr, npa2d)

In [96]:
np.load('data/both.npz')

In [97]:
d = np.load('data/both.npz')

In [98]:
d.files

['arr_0', 'arr_1']

In [99]:
d[d.files[0]]

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [100]:
d[d.files[1]]

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

### Concatenate and sorting

In [101]:
npa2d

array([[0., 2.],
       [3., 0.],
       [5., 6.]])

In [102]:
np.concatenate([npa2d, npa2d], axis=0)

array([[0., 2.],
       [3., 0.],
       [5., 6.],
       [0., 2.],
       [3., 0.],
       [5., 6.]])

In [103]:
np.concatenate([npa2d, npa2d], axis=1)

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [5., 6., 5., 6.]])

In [104]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [5., 6.],
       [0., 2.],
       [3., 0.],
       [5., 6.]])

In [105]:
np.hstack([npa2d, npa2d])

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [5., 6., 5., 6.]])

In [106]:
npa = np.hstack([npa2d, npa2d])

In [107]:
npa

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [5., 6., 5., 6.]])

In [108]:
npa.sort()

In [109]:
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [5., 5., 6., 6.]])

### Working with dates

In [110]:
d = np.datetime64('2020-12-01 23:34:23')

In [111]:
d

numpy.datetime64('2020-12-01T23:34:23')

In [112]:
# sec
d + 10

numpy.datetime64('2020-12-01T23:34:33')

In [113]:
# one day
oneday = np.timedelta64(1, 'D')

In [114]:
oneday

numpy.timedelta64(1,'D')

In [115]:
d + oneday

numpy.datetime64('2020-12-02T23:34:23')

In [116]:
# minute
oneminute = np.timedelta64(1, 'm')

In [117]:
d + oneminute

numpy.datetime64('2020-12-01T23:35:23')

### End.